### PR TITLE
Remove as much hashed names as possible from intermediary publication 

### LINKED ISSUE #334: `C_cifoaixd$C_lcybgaxw$C_amqftyfx$C_iinezlaz` is broken
Its in ChunkBuilder.BuiltChunk.RebuildTask. I found it by that class' render method, its return value is that class `C_cifoaixd$C_lcybgaxw$C_amqftyfx$C_iinezlaz` and it is very broken. It wont let me import it. `C_cifoaixd$C_lcybgaxw$C_amqftyfx` (the first part of it) just maps to `ChunkBuilder.BuiltChunk.RebuildTask`. I dont know what else to put here.

### PR DESCRIPTION
**Pull request by IotaBread**
Depends on #370, replaces #330. Better reviewed by filtering out commits from #370. Doesn't fix #334 yet

- Removes `buildTinyWithEnum` task, as it was broken and used just by `remapUnpickDefinitions`
  - Replaced by `mergeTinyV2`, which includes the changes from `insertAutoGeneratedMappings`
- Tiny merge tasks no longer fill namespaces
- Unobfuscated methods now keep their name, even when `intermediary` would override them
- `remapUnpickDefinitions` fills the namespace it needs during runtime, and doesn't apply those changes to a file, which would add unnecessary mappings
- Added a bunch of buildscript tests for these changes

Can't be merged until #334 is fixed

### CODE REVIEW

**Comment by IotaBread** [comment]
Alright, the pr should be good to review. Here's a quick summary of the changes this introduces:
- Unmapped methods and fields should no longer have hashed names within the intermediary publication.
- Completely unmapped classes shouldn't contain any hashed names either.
- Due to the structure of the Tiny V2 mappings format, unmapped classes with at least one entry or comment in them will use their hashed name
  - This is required to fix remapping issues with inner classes of unmapped ones.
  - This isn't needed for unmapped classes without any named inner class, but I haven't found a good way to solve this, so it's going to have to be like this for now
  - The Enigma Tiny V2 writer also saves unmapped classes as named with their hashed names, so some extra work is needed there to fix this
    - > Most of the time this isn't an issue since most classes in the tree have a mapping, but it does become an issue when the class, without a mapping, has a non-class child in the tree

**Review by OroArmor — APPROVED** [review]

File: buildSrc/src/main/java/quilt/internal/mappingio/UnmappedNameRemoverVisitor.java [hunk 1]
```diff
@@ -12,7 +12,7 @@
 
 /**
  * Removes unmapped names from the {@link #targetNamespace target namespace}. Whether a name is unmapped is determined
- * by {@link #unmappedPredicate}
+ * either if it's name on the target namespace is the same as on the {@link #unmappedNamespace unmapped one}, or by {@link #unmappedPredicate}
```
Comment (eristhea) [inline buildSrc/src/main/java/quilt/internal/mappingio/UnmappedNameRemoverVisitor.java]:
```suggestion
 * either if its name on the target namespace is the same as on the {@link #unmappedNamespace unmapped one}, or by {@link #unmappedPredicate}
```

**Review by eristhea — COMMENTED** [review]
absolutely love the tests :)

**Review by eristhea — APPROVED** [review]
